=== IzaalalaCoder/Hexagonia/hex/src/main/resources/informations/save.dtd
<!ELEMENT save (data, board, history) >
<!ELEMENT data (computer?, current, end) >
<!ELEMENT computer EMPTY>
<!ELEMENT current (#PCDATA)>
<!ELEMENT end (#PCDATA)>
<!ELEMENT board (row+) >
<!ELEMENT row (cell+) >
<!ELEMENT cell (#PCDATA) >
<!ATTLIST player mode (human | computer) #REQUIRED>
<!ATTLIST computer level (EASY | MEDIUM | HARD) #REQUIRED>
<!ELEMENT history (act*) >
<!ELEMENT act (coordinate, p) >
<!ELEMENT coordinate (abscissa, ordinate) >
<!ELEMENT p (#PCDATA) >
<!ELEMENT abscissa (#PCDATA) >
<!ELEMENT ordinate (#PCDATA) >

=== IzaalalaCoder/Hexagonia/hex/src/main/resources/informations/example_save.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE save SYSTEM "save.dtd">

<save>
    <data>
        <computer level="EASY"></computer>
        <current>0</current>
    </data>
    <board>
        <row>
            <cell />
            <cell>0</cell>
            <cell></cell>
            <cell />
        </row>
        <row>
            <cell>0</cell>
            <cell />
            <cell />
            <cell>1</cell>
        </row>
        <row>
            <cell>0</cell>
            <cell />
            <cell>1</cell>
            <cell>1</cell>
        </row>
        <row>
            <cell>0</cell>
            <cell />
            <cell />
            <cell>0</cell>
        </row>
    </board>
</save>

=== IzaalalaCoder/Hexagonia/newSave.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE save SYSTEM "save.dtd">
<save>
  <data>
    <current>0</current>
    <end>0</end>
  </data>
  <board>
    <row>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
    </row>
    <row>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell>0</cell>
      <cell>0</cell>
      <cell/>
    </row>
    <row>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell>1</cell>
      <cell/>
    </row>
    <row>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell>1</cell>
      <cell/>
      <cell/>
    </row>
    <row>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
    </row>
    <row>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
    </row>
    <row>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
    </row>
    <row>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
    </row>
    <row>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
    </row>
    <row>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
      <cell/>
    </row>
  </board>
  <history>
    <act>
      <coordinate>
        <abscissa>1</abscissa>
        <ordinate>7</ordinate>
      </coordinate>
      <p>0</p>
    </act>
    <act>
      <coordinate>
        <abscissa>3</abscissa>
        <ordinate>7</ordinate>
      </coordinate>
      <p>1</p>
    </act>
    <act>
      <coordinate>
        <abscissa>1</abscissa>
        <ordinate>8</ordinate>
      </coordinate>
      <p>0</p>
    </act>
    <act>
      <coordinate>
        <abscissa>2</abscissa>
        <ordinate>8</ordinate>
      </coordinate>
      <p>1</p>
    </act>
  </history>
</save>
